name: flutter_architecture
description: 'Showcase of modern Flutter app clean architecture with melos'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.4.4
  util:
    path: packages/util
  presentation:
    path: packages/presentation

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  melos: ^6.2.0
  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true