name: infrastructure
description: "A module with external data sources and services"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.4.4
  shared_preferences: ^2.3.3
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2